const assert=require('assert'),fs=require('fs'),vm=require('vm');const data={},memory=new Map();const fDb={ref:(_,path)=>({path}),get:async r=>({val:()=>data[r.path]||null}),runTransaction:async(r,fn)=>{const next=fn(data[r.path]||null);if(next===undefined)return{committed:false};data[r.path]=JSON.parse(JSON.stringify(next));return{committed:true,snapshot:{val:()=>data[r.path]}}}};
const c={console,fDb,db:{},firebaseReady:true,starterVocabulary:[],localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)}};vm.createContext(c);for(const f of ['gacha-core.js','store.js'])vm.runInContext(fs.readFileSync('assets/js/'+f,'utf8').replace(/^import .*;\n/gm,'').replace(/export /g,''),c);const run=s=>vm.runInContext(s,c);
(async()=>{
assert.deepEqual(Array.from(run("RARITIES.map(r=>CHARACTERS.filter(c=>c.rank===r.rank).length)")),[2,2,1,1,1]);for(const [x,rank]of [[0,'C'],[.51,'B'],[.81,'A'],[.95,'S'],[.995,'SS']])assert.equal(run(`chooseCharacter(${x}).rank`),rank);
for(const score of [0,70,74]){await run(`awardGachaTicket({uid:'u'},{mode:'listening-stress',total:20,score:${score},attemptId:'fail${score}'})`);assert.equal(data['users/u/gacha'].tickets,0);}
await run("awardGachaTicket({uid:'u'},{mode:'meaning',total:20,score:100,attemptId:'wrong-mode'})");assert.equal(data['users/u/gacha'].tickets,0);
await Promise.all([run("awardGachaTicket({uid:'u'},{mode:'listening-stress',total:20,score:75,attemptId:'pass'})"),run("awardGachaTicket({uid:'u'},{mode:'listening-stress',total:20,score:75,attemptId:'pass'})")]);assert.equal(data['users/u/gacha'].tickets,1);
await run("drawGacha({uid:'u'},'draw1','aurora')");assert.equal(data['users/u/gacha'].tickets,0);assert.equal(data['users/u/gacha'].inventory.aurora,1);assert.equal(data['users/u/gacha'].equipped,'aurora');await run("drawGacha({uid:'u'},'draw1','aurora')");assert.equal(data['users/u/gacha'].inventory.aurora,1);await assert.rejects(run("drawGacha({uid:'u'},'draw2','mochi')"));await assert.rejects(run("equipGacha({uid:'u'},'mochi')"));await run("equipGacha({uid:'u'},'')");assert.equal(data['users/u/gacha'].equipped,'');assert.equal((await run("getGacha({uid:'other'})")).tickets,0);
await run("awardGachaTicket({uid:'demo',isDemo:true},{mode:'listening-stress',total:20,score:100,attemptId:'demo-pass'})");await run("drawGacha({uid:'demo',isDemo:true},'demo-draw','mochi')");assert.equal((await run("getGacha({uid:'demo',isDemo:true})")).inventory.mochi,1);
data['users/seller/gacha']={tickets:0,inventory:{mochi:2,pico:1,minto:2,luna:1,nova:1,aurora:1},equipped:'aurora'};
await assert.rejects(run("sellGacha({uid:'seller'},'bad',{minto:2})"));assert.equal(data['users/seller/gacha'].tickets,0);
await run("sellGacha({uid:'seller'},'basic',{mochi:2,pico:1})");assert.equal(data['users/seller/gacha'].tickets,1);assert(!data['users/seller/gacha'].inventory.mochi);
await run("sellGacha({uid:'seller'},'basic',{mochi:2,pico:1})");assert.equal(data['users/seller/gacha'].tickets,1);
await run("sellGacha({uid:'seller'},'rare',{luna:1,nova:1,aurora:1})");assert.equal(data['users/seller/gacha'].tickets,7);assert.equal(data['users/seller/gacha'].equipped,'');assert.equal(data['users/seller/gacha'].inventory.minto,2);
for(const value of ['{minto:3}','{minto:-3}','{minto:1.5}','{unknown:3}'])await assert.rejects(run(`sellGacha({uid:'seller'},'invalid'+${JSON.stringify(value)},${value})`));assert.equal(data['users/seller/gacha'].tickets,7);
console.log('PASS: rarity, ticket rewards, draw deduplication, wallet isolation, 3 mixed C/B = 1 ticket, A/S/SS = 1/2/3, sale retry guard, oversell rejection and last-copy companion removal.');
})().catch(e=>{console.error(e);process.exitCode=1});
