const fs=require('fs'),vm=require('vm'),assert=require('assert');const els=new Map();function el(k){if(!els.has(k)){const classes=new Set();els.set(k,{value:'',innerHTML:'',textContent:'',style:{setProperty(){}},classList:{add:k=>classes.add(k),remove:k=>classes.delete(k),contains:k=>classes.has(k),toggle(){}},addEventListener(){},focus(){},setSelectionRange(){},querySelectorAll(){return []},showModal(){},close(){}})}return els.get(k)}
let recorded=[];const vocab=[{id:'w1',word:'hello',meaning:'xin chào',session:1},{id:'w2',word:'bye',meaning:'tạm biệt',session:1},{id:'w3',word:'thanks',meaning:'cảm ơn',session:2}];
const c={console,setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},document:{querySelector:el,querySelectorAll:()=>[],body:el('body')},window:{scrollTo(){},addEventListener(){}},navigator:{},localStorage:{getItem:()=>null,setItem(){}},firebaseReady:false,firebaseConfig:{authDomain:'example.com'},auth:{},fAuth:{},isFirebaseConfigured:()=>false,store:{setStoreUser(){},ensureUserProfile:async()=>({role:'teacher',displayName:'Teacher'}),getVocabulary:async()=>vocab,getCurriculum:async()=>({categories:[],lessons:[]}),getProgress:async()=>({}),getTestResults:async()=>[],getLeaderboard:async()=>[],updateWordProgress:async(u,id,patch)=>recorded.push({id,patch})},aiLookup(){},searchCommonsImages(){},confirm:()=>true};vm.createContext(c);
for(const f of ['curriculum.js','ideas.js'])vm.runInContext(fs.readFileSync('assets/js/'+f,'utf8').replace(/export /g,''),c);
vm.runInContext(fs.readFileSync('assets/js/app.js','utf8').replace(/^import .*;\n/gm,''),c);const run=s=>vm.runInContext(s,c);
(async()=>{await run("bootstrapUser({uid:'t1',displayName:'Teacher'})");assert(el('#viewRoot').innerHTML.includes('Danh mục & buổi học'));assert(run('canTeach()'));assert(!run('isAdmin()'));
run("state.vocabSession='1';state.category='all'");assert.equal(run('filteredVocab().length'),2);
run("renderSessions()");assert(el('#viewRoot').innerHTML.includes('Đồ vật &amp; cuộc sống'));
run("state.profile.role='student';state.view='dashboard';navigate('admin')");assert.equal(run('state.view'),'dashboard');
run("state.session=1;startLearningGame('spelling')");el('#gameAnswer').value=run('state.game.words[0].word');await el('#wordGameForm').onsubmit({preventDefault(){}});assert.equal(run('state.game.correct'),1);assert(recorded[0].patch.mastered);
run("state.game=null;state.session=1;startLearningGame('scramble')");el('#gameAnswer').value='wrong';await el('#wordGameForm').onsubmit({preventDefault(){}});assert.equal(run('state.game.correct'),0);assert.equal(recorded.at(-1).patch.wrongCount,1);
run("renderIdeas()");assert.equal((el('#viewRoot').innerHTML.match(/class=\"panel idea-card\"/g)||[]).length,100);run("state.ideaGroup='Nghe hiểu';renderIdeas()");assert.equal((el('#viewRoot').innerHTML.match(/class=\"panel idea-card\"/g)||[]).length,10);
console.log('PASS: teacher content view, student guard, lesson-specific vocabulary, named sessions, spelling/scramble progression, ideas filtering.');})().catch(e=>{console.error(e);process.exitCode=1});
