const fs=require('fs'),vm=require('vm'),assert=require('assert');let requests=[];
const c={URL,URLSearchParams,AbortSignal,setTimeout,clearTimeout,fetch:async url=>{requests.push(url);if(url.includes('dictionaryapi.dev'))return {ok:!url.includes('fallback'),json:async()=>[{license:{name:'CC BY-SA'},phonetics:[{audio:'https://api.dictionaryapi.dev/media/pronunciations/en/book-uk.mp3'},{audio:'https://api.dictionaryapi.dev/media/pronunciations/en/book-us.mp3'}]}]};if(url.includes('action=parse'))return {ok:true,json:async()=>({parse:{wikitext:{'*':'==English==\n{{audio|en|En-us-fallback.ogg|Audio}}\n==French==\n{{audio|fr|French.ogg}}'}}})};return {ok:true,json:async()=>({query:{pages:{one:{title:'File:En-us-fallback.ogg',imageinfo:[{url:'https://upload.wikimedia.org/fallback.ogg',descriptionurl:'https://commons.wikimedia.org/wiki/File:En-us-fallback.ogg',extmetadata:{LicenseShortName:{value:'CC BY-SA'}}}]}}}})};}};vm.createContext(c);vm.runInContext(fs.readFileSync('assets/js/pronunciation-audio.js','utf8').replace(/export /g,''),c);const run=s=>vm.runInContext(s,c);
(async()=>{
 assert.equal(run("safePronunciationUrl('javascript:alert(1)')"),'');assert.equal(run("safePronunciationUrl('https://evil.example/hello.mp3')"),'');assert.equal(run("safePronunciationUrl('//ssl.gstatic.com/hello.mp3')"),'https://ssl.gstatic.com/hello.mp3');
 const record=await run("lookupPronunciationAudio('book')");assert(record.url.includes('book-us'));assert.equal(record.license,'CC BY-SA');const count=requests.length;await run("lookupPronunciationAudio('book')");assert.equal(requests.length,count);
 const fallback=await run("lookupPronunciationAudio('fallback')");assert.equal(fallback.url,'https://upload.wikimedia.org/fallback.ogg');assert.equal(fallback.license,'CC BY-SA');assert(!requests.some(url=>url.includes('French.ogg')));
 c.Audio=class{constructor(url){this.src=url;this.listeners={}}addEventListener(name,fn){this.listeners[name]=fn}removeEventListener(name){delete this.listeners[name]}load(){this.listeners.canplaythrough()}};
 assert.equal((await run("loadPronunciationElement('https://upload.wikimedia.org/ready.ogg')")).src,'https://upload.wikimedia.org/ready.ogg');
 c.Audio=class{constructor(url){this.src=url;this.listeners={}}addEventListener(name,fn){this.listeners[name]=fn}removeEventListener(name){delete this.listeners[name]}load(){this.listeners.error()}};
 await assert.rejects(run("loadPronunciationElement('https://upload.wikimedia.org/bad.ogg')"),/Không đọc/);
 console.log('PASS: trusted HTTPS audio URLs, US voice preference, cached dictionary audio, English-only Wiktionary fallback, source/license, audio preload success and failure.');
})().catch(e=>{console.error(e);process.exitCode=1});
